name: Create Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          check-latest: true

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run package

      - name: ZIP-Archiv für EXE-Dateien erstellen
        shell: pwsh
        run: |
          Set-Location .\release\build
          $zipDateiName = "windows-release.zip"
          $exeDateien = Get-ChildItem -Path . -Include *.exe
          if ($exeDateien.Count -eq 0) {
            Write-Host "Keine EXE-Dateien gefunden."
            exit 1
          }
          Compress-Archive -Path $exeDateien.FullName -DestinationPath $zipDateiName

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release/win-release.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ github.ref }}
